server:
  port: 8082

spring:
  application:
    name: transaction-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/transactiondb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    config:
      uri: http://localhost:8888
  profiles:
    active: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
